### ISSUE TITLE
Email Templates are not binding the Project information while sending out emails to the users

### ISSUE THREAD

**Issue by Milstein** [nerc-project/coldfront-nerc#76]
The customized email templates used on NERC's ColdFront, located [here](https://github.com/nerc-project/coldfront-nerc/tree/main/src/email) has issue with project information. For example, for project allocations expiring soon is rendered like the following (Without the project infos):
```
Dear New England Research Cloud user,

Your access to New England Research Cloud's resources is expiring soon. Failure to renew the expiring allocation(s) on time will terminate access to the resource
for all users on the allocation. To renew, login to ColdFront and complete the short renewal process for each expiring allocation.  Below is a list of links to
your project(s) containing at least one expiring allocation:

The group owner responsible for this project is required to renew it on a yearly basis. If you have not done so in the
last year, you will be required to before renewing the allocation.
For more information about the yearly renewal, visit our knowledge base: https://nerc.mghpcc.org/user-guides/

Thank you,
New England Research Cloud (NERC)
https://nerc.mghpcc.org/
https://nerc-project.github.io/nerc-docs
https://nerc.instatus.com/
```

**Comment by knikolla** [comment]
I believe the issue is that the template is trying to access elements of the tuple by doing `.0`, which is not valid python.

https://github.com/ubccr/coldfront/blob/6b913f8bdbcfb1dcc7083f77e82f1fddd6c811f8/coldfront/templates/email/allocation_expiring.txt#L8-L9

```>>> a = (1, 2)
>>> a.0
  File "<stdin>", line 1
    a.0
     ^^
SyntaxError: invalid syntax
>>> a[0]
1
>>> 
```

**Comment by knikolla** [comment]
Well, I take that back. It looks like dot notation is a valid way to access tuples and dictionaries in Django templates.

https://docs.djangoproject.com/en/4.1/topics/templates/#variables

**Comment by knikolla** [comment]
Ah, the template and what ColdFront sends to the template has changed since the last time we pulled. So there is no project_dict. https://github.com/ubccr/coldfront/commit/b6a051b0930ff560158f46b6d00291f665ce166b
